baseurl = "http://eherdtersmith.rbind.io/"
title = "Elizabeth Herdter Smith, Ph.D."
author = "Elizabeth Herdter Smith, Ph.D."
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Elizabeth Herdter Smith, Ph.D."

[[menu.main]]
    name = "Home"
    url = "http://eherdtersmith.rbind.io/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/eherdter"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/elizabeth-herdter"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/liz_herdter"
    weight = 4
